### ISSUE TITLE
首页列表item点击即闪退~

### ISSUE THREAD

**Issue by stay4cold** [HotBitmapGG/StudyProject#1]
06-06 17:00:31.816 22302-22302/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.hotbitmapgg.studyproject, PID: 22302
                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{com.hotbitmapgg.studyproject/com.hotbitmapgg.studyproject.hcc.ui.activity.GankDetailsActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2218)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2268)
                                                       at android.app.ActivityThread.access$800(ActivityThread.java:145)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1206)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:136)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5094)
                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:893)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:702)
                                                       at dalvik.system.NativeStart.main(Native Method)
                                                    Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
                                                       at android.support.v7.app.AppCompatDelegateImplV7.createSubDecor(AppCompatDelegateImplV7.java:343)
                                                       at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:312)
                                                       at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:277)
                                                       at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                                                       at com.hotbitmapgg.studyproject.hcc.base.AbsBaseActivity.onCreate(AbsBaseActivity.java:33)
                                                       at android.app.Activity.performCreate(Activity.java:5242)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2172)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2268) 
                                                       at android.app.ActivityThread.access$800(ActivityThread.java:145) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1206) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:136) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5094) 
                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:515) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:893) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:702) 
                                                       at dalvik.system.NativeStart.main(Native Method)

**Comment by HotBitmapGG** [comment]
请问你手机的版本是多少啊

**Comment by HotBitmapGG** [comment]
已经修复.
