### ISSUE TITLE
这个问题如何解决！

### ISSUE THREAD

**Issue by sunhacker** [HotBitmapGG/StudyProject#2]
java.lang.NoSuchMethodError: com.hotbitmapgg.studyproject.hcc.ui.fragment.HomeFragment.getChildFragmentManager
                                                                                at com.hotbitmapgg.studyproject.hcc.ui.fragment.HomeFragment.initViews(HomeFragment.java:57)
                                                                                at com.hotbitmapgg.studyproject.hcc.base.LazyFragment.onViewCreated(LazyFragment.java:31)
                                                                                at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:842)
                                                                                at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1032)
                                                                                at android.app.BackStackRecord.run(BackStackRecord.java:622)
                                                                                at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1382)
                                                                                at android.app.Activity.performStart(Activity.java:4475)
                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1929)
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1981)
                                                                                at android.app.ActivityThread.access$600(ActivityThread.java:123)
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1147)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                at android.os.Looper.loop(Looper.java:137)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:4424)
                                                                                at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                at java.lang.reflect.Method.invoke(Method.java:511)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
                                                                                at dalvik.system.NativeStart.main(Native Method)
这个问题如何解决！

**Comment by HotBitmapGG** [comment]
这个问题是应该是你导包的问题，你导入项目，注意getChildFragmentManager这个方法在android.support.v4.app.Fragment这个库是没有这个方法的，我使用的是android.app.Fragment下的Fragment，项目中也引用了V13的兼容库，也可以导入V13来使用。

**Comment by sunhacker** [comment]
提示信息是说版本低了，这个可有解决办法：Call requires API level 17 (current min is 15): android.app.Fragment#getChildFragmentManager，

**Comment by HotBitmapGG** [comment]
调用需要API级别17，当前最小值是15 ，把minSdkVersion 这个地方改一下

**Comment by sunhacker** [comment]
怎样才能使用15版本的呢？

**Comment by HotBitmapGG** [comment]
现在已全部修改
